# Site settings
title: GleepGurgleGuu
email: ""
description: ""
baseurl: ""
url: "http://vermiculuscaro.github.io"

# Build settings
markdown: kramdown

permalink: /:title.html
exclude:
  - README.md

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  auto_ids: false
  syntax_highlighter_opts:
    disable : true
  typographic_symbols: {hellip: ..., mdash: ---, ndash: --}